[package]
name = "b2_backup"
version = "0.1.0"
authors = ["Adam Reichold <adam.reichold@t-online.de>"]
license = "GPL-3.0"
repository = "https://github.com/adamreichold/b2_backup"
edition = "2018"

[dependencies]
attohttpc = { version = "0.5", default-features = false, features = ["json", "tls"] }
base64 = "0.11"
hex = "0.4"
libc = "0.2"
lru-cache = "0.1"
openssl = "0.10"
rayon = "1.2"
rusqlite = { git = "https://github.com/jgallagher/rusqlite.git", features = ["bundled", "buildtime_bindgen", "session"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
tempfile = "3.1"
zstd = { version = "0.5", default-features = false }

[profile.release]
opt-level = "s"
lto = true
